/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ae42716d-f5c6-4a00-b0a8-750e09c68be0",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_uLo8MS9RH",
    "aws_user_pools_web_client_id": "210h3vpfkquqh2kpq62c4gmt98",
    "oauth": {}
};


export default awsmobile;
